version: 2.1

orbs:
  unity: game-ci/unity@1.7.0

workflows:
  build-unity-project:
    jobs:
      - unity/create-activation-file
      - deploy-job:
          steps:
            - add_ssh_keys:
                fingerprints:
                  - "SO:ME:FIN:G:ER:PR:IN:T"
                  - "SHA256:4jIO71cNaIekPILl3bIK8df2ux5YWa/ls8TNQo+AsjE"
      - unity/build:
          name: 'build-windows64-il2cpp'
          step-name: 'Build StandaloneWindows64'
          executor:
            name: 'unity/windows-2022'
            target_platform: 'windows-il2cpp'
            editor_version: '2021.3.2f1'
          build-target: StandaloneWindows64
          compress: true
          context: unity
