//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.3.0
//     from Assets/Modules/Input/PlayerInputActions.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @PlayerInputActions : IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @PlayerInputActions()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""PlayerInputActions"",
    ""maps"": [
        {
            ""name"": ""Player"",
            ""id"": ""cbe1b8aa-f5ef-4600-ad44-523c36131066"",
            ""actions"": [
                {
                    ""name"": ""Shoot0"",
                    ""type"": ""Button"",
                    ""id"": ""2b39f451-ea30-46ef-aebf-d04a3a2c7b81"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Shoot1"",
                    ""type"": ""Button"",
                    ""id"": ""214b2d49-da75-4d59-8315-bda37ca19b99"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Shoot2"",
                    ""type"": ""Button"",
                    ""id"": ""9c57393a-7ef8-46da-a61a-1288e2d96611"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Shoot3"",
                    ""type"": ""Button"",
                    ""id"": ""d51a1266-75f1-4294-ab8c-0bca26c48c83"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Shoot4"",
                    ""type"": ""Button"",
                    ""id"": ""c052a96c-c9cb-417e-b376-18ee2695bdc7"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Shoot5"",
                    ""type"": ""Button"",
                    ""id"": ""f1bd1511-ecad-4183-bc92-d3d33aab3528"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Shoot6"",
                    ""type"": ""Button"",
                    ""id"": ""e61fbb54-ccc3-49e7-8e8b-251ab4eeb84b"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Shoot7"",
                    ""type"": ""Button"",
                    ""id"": ""f901222c-3b73-4904-9a1a-5b7e17fc03cb"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Shoot8"",
                    ""type"": ""Button"",
                    ""id"": ""32c0e637-f125-4885-8d8f-2d70cdf83c0f"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Shoot9"",
                    ""type"": ""Button"",
                    ""id"": ""8de3d60e-01fd-4768-bea0-5041afbff8b0"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Pause"",
                    ""type"": ""Button"",
                    ""id"": ""d261984d-94a7-4da4-9507-b2e8f3e6f06c"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""f2149717-adf7-4de0-8abc-5fe3adfe3bd1"",
                    ""path"": ""<Keyboard>/numpad0"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Shoot0"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""bbbc9ede-ef5a-4174-bfc7-96e123b94e48"",
                    ""path"": ""<Keyboard>/0"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Shoot0"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""b100ca65-01ba-4430-b5d9-ff91e6487104"",
                    ""path"": ""<Keyboard>/numpad1"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Shoot1"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""0eded96c-9618-4042-a8e2-feec7c8c589d"",
                    ""path"": ""<Keyboard>/1"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Shoot1"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""f6a311de-b878-493c-9d2b-0dcdd3e3ca77"",
                    ""path"": ""<Keyboard>/numpad2"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Shoot2"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""b1be2970-2154-4c4d-967c-0bafe0a21886"",
                    ""path"": ""<Keyboard>/2"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Shoot2"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""cbe10d87-1f47-4b05-af12-05f2b3558fb3"",
                    ""path"": ""<Keyboard>/numpad3"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Shoot3"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""f4025969-6e74-42ca-af56-73ae2edf4a5b"",
                    ""path"": ""<Keyboard>/3"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Shoot3"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""b890f1d6-af1b-4cf1-ac26-1c62c31e2403"",
                    ""path"": ""<Keyboard>/numpad4"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Shoot4"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""d5b07a55-8849-4d94-9bf1-c4d2b82905a6"",
                    ""path"": ""<Keyboard>/4"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Shoot4"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""3eeab691-d1e2-4c04-b1be-bad8f4bb60d2"",
                    ""path"": ""<Keyboard>/numpad5"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Shoot5"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""72287ad1-b780-45c4-ab0d-f301b2b041ce"",
                    ""path"": ""<Keyboard>/5"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Shoot5"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""fffd74a5-1bba-432c-9796-ed5c75b7b50b"",
                    ""path"": ""<Keyboard>/numpad6"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Shoot6"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""874892b2-e90a-48e3-8472-60ce286d217a"",
                    ""path"": ""<Keyboard>/6"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Shoot6"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""f8794acf-1590-4068-8f0a-db5093a4c194"",
                    ""path"": ""<Keyboard>/numpad7"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Shoot7"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""ffbdc3b5-33dd-44b7-ad8e-738b1f91498c"",
                    ""path"": ""<Keyboard>/7"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Shoot7"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""b985eaec-cc71-42a6-ac47-610f2a20cea4"",
                    ""path"": ""<Keyboard>/numpad8"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Shoot8"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""38ade6ba-3e04-444a-9428-8c73c0b0ad1b"",
                    ""path"": ""<Keyboard>/8"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Shoot8"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""0c96b0cb-22e4-469b-922a-382473394d94"",
                    ""path"": ""<Keyboard>/numpad9"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Shoot9"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""1f4690b6-6ec1-471a-9df2-1f1cefb4bd34"",
                    ""path"": ""<Keyboard>/9"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Shoot9"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""10491975-7b95-41e7-aa12-db9057003ed9"",
                    ""path"": ""<Keyboard>/escape"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Pause"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // Player
        m_Player = asset.FindActionMap("Player", throwIfNotFound: true);
        m_Player_Shoot0 = m_Player.FindAction("Shoot0", throwIfNotFound: true);
        m_Player_Shoot1 = m_Player.FindAction("Shoot1", throwIfNotFound: true);
        m_Player_Shoot2 = m_Player.FindAction("Shoot2", throwIfNotFound: true);
        m_Player_Shoot3 = m_Player.FindAction("Shoot3", throwIfNotFound: true);
        m_Player_Shoot4 = m_Player.FindAction("Shoot4", throwIfNotFound: true);
        m_Player_Shoot5 = m_Player.FindAction("Shoot5", throwIfNotFound: true);
        m_Player_Shoot6 = m_Player.FindAction("Shoot6", throwIfNotFound: true);
        m_Player_Shoot7 = m_Player.FindAction("Shoot7", throwIfNotFound: true);
        m_Player_Shoot8 = m_Player.FindAction("Shoot8", throwIfNotFound: true);
        m_Player_Shoot9 = m_Player.FindAction("Shoot9", throwIfNotFound: true);
        m_Player_Pause = m_Player.FindAction("Pause", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }
    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }
    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // Player
    private readonly InputActionMap m_Player;
    private IPlayerActions m_PlayerActionsCallbackInterface;
    private readonly InputAction m_Player_Shoot0;
    private readonly InputAction m_Player_Shoot1;
    private readonly InputAction m_Player_Shoot2;
    private readonly InputAction m_Player_Shoot3;
    private readonly InputAction m_Player_Shoot4;
    private readonly InputAction m_Player_Shoot5;
    private readonly InputAction m_Player_Shoot6;
    private readonly InputAction m_Player_Shoot7;
    private readonly InputAction m_Player_Shoot8;
    private readonly InputAction m_Player_Shoot9;
    private readonly InputAction m_Player_Pause;
    public struct PlayerActions
    {
        private @PlayerInputActions m_Wrapper;
        public PlayerActions(@PlayerInputActions wrapper) { m_Wrapper = wrapper; }
        public InputAction @Shoot0 => m_Wrapper.m_Player_Shoot0;
        public InputAction @Shoot1 => m_Wrapper.m_Player_Shoot1;
        public InputAction @Shoot2 => m_Wrapper.m_Player_Shoot2;
        public InputAction @Shoot3 => m_Wrapper.m_Player_Shoot3;
        public InputAction @Shoot4 => m_Wrapper.m_Player_Shoot4;
        public InputAction @Shoot5 => m_Wrapper.m_Player_Shoot5;
        public InputAction @Shoot6 => m_Wrapper.m_Player_Shoot6;
        public InputAction @Shoot7 => m_Wrapper.m_Player_Shoot7;
        public InputAction @Shoot8 => m_Wrapper.m_Player_Shoot8;
        public InputAction @Shoot9 => m_Wrapper.m_Player_Shoot9;
        public InputAction @Pause => m_Wrapper.m_Player_Pause;
        public InputActionMap Get() { return m_Wrapper.m_Player; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(PlayerActions set) { return set.Get(); }
        public void SetCallbacks(IPlayerActions instance)
        {
            if (m_Wrapper.m_PlayerActionsCallbackInterface != null)
            {
                @Shoot0.started -= m_Wrapper.m_PlayerActionsCallbackInterface.OnShoot0;
                @Shoot0.performed -= m_Wrapper.m_PlayerActionsCallbackInterface.OnShoot0;
                @Shoot0.canceled -= m_Wrapper.m_PlayerActionsCallbackInterface.OnShoot0;
                @Shoot1.started -= m_Wrapper.m_PlayerActionsCallbackInterface.OnShoot1;
                @Shoot1.performed -= m_Wrapper.m_PlayerActionsCallbackInterface.OnShoot1;
                @Shoot1.canceled -= m_Wrapper.m_PlayerActionsCallbackInterface.OnShoot1;
                @Shoot2.started -= m_Wrapper.m_PlayerActionsCallbackInterface.OnShoot2;
                @Shoot2.performed -= m_Wrapper.m_PlayerActionsCallbackInterface.OnShoot2;
                @Shoot2.canceled -= m_Wrapper.m_PlayerActionsCallbackInterface.OnShoot2;
                @Shoot3.started -= m_Wrapper.m_PlayerActionsCallbackInterface.OnShoot3;
                @Shoot3.performed -= m_Wrapper.m_PlayerActionsCallbackInterface.OnShoot3;
                @Shoot3.canceled -= m_Wrapper.m_PlayerActionsCallbackInterface.OnShoot3;
                @Shoot4.started -= m_Wrapper.m_PlayerActionsCallbackInterface.OnShoot4;
                @Shoot4.performed -= m_Wrapper.m_PlayerActionsCallbackInterface.OnShoot4;
                @Shoot4.canceled -= m_Wrapper.m_PlayerActionsCallbackInterface.OnShoot4;
                @Shoot5.started -= m_Wrapper.m_PlayerActionsCallbackInterface.OnShoot5;
                @Shoot5.performed -= m_Wrapper.m_PlayerActionsCallbackInterface.OnShoot5;
                @Shoot5.canceled -= m_Wrapper.m_PlayerActionsCallbackInterface.OnShoot5;
                @Shoot6.started -= m_Wrapper.m_PlayerActionsCallbackInterface.OnShoot6;
                @Shoot6.performed -= m_Wrapper.m_PlayerActionsCallbackInterface.OnShoot6;
                @Shoot6.canceled -= m_Wrapper.m_PlayerActionsCallbackInterface.OnShoot6;
                @Shoot7.started -= m_Wrapper.m_PlayerActionsCallbackInterface.OnShoot7;
                @Shoot7.performed -= m_Wrapper.m_PlayerActionsCallbackInterface.OnShoot7;
                @Shoot7.canceled -= m_Wrapper.m_PlayerActionsCallbackInterface.OnShoot7;
                @Shoot8.started -= m_Wrapper.m_PlayerActionsCallbackInterface.OnShoot8;
                @Shoot8.performed -= m_Wrapper.m_PlayerActionsCallbackInterface.OnShoot8;
                @Shoot8.canceled -= m_Wrapper.m_PlayerActionsCallbackInterface.OnShoot8;
                @Shoot9.started -= m_Wrapper.m_PlayerActionsCallbackInterface.OnShoot9;
                @Shoot9.performed -= m_Wrapper.m_PlayerActionsCallbackInterface.OnShoot9;
                @Shoot9.canceled -= m_Wrapper.m_PlayerActionsCallbackInterface.OnShoot9;
                @Pause.started -= m_Wrapper.m_PlayerActionsCallbackInterface.OnPause;
                @Pause.performed -= m_Wrapper.m_PlayerActionsCallbackInterface.OnPause;
                @Pause.canceled -= m_Wrapper.m_PlayerActionsCallbackInterface.OnPause;
            }
            m_Wrapper.m_PlayerActionsCallbackInterface = instance;
            if (instance != null)
            {
                @Shoot0.started += instance.OnShoot0;
                @Shoot0.performed += instance.OnShoot0;
                @Shoot0.canceled += instance.OnShoot0;
                @Shoot1.started += instance.OnShoot1;
                @Shoot1.performed += instance.OnShoot1;
                @Shoot1.canceled += instance.OnShoot1;
                @Shoot2.started += instance.OnShoot2;
                @Shoot2.performed += instance.OnShoot2;
                @Shoot2.canceled += instance.OnShoot2;
                @Shoot3.started += instance.OnShoot3;
                @Shoot3.performed += instance.OnShoot3;
                @Shoot3.canceled += instance.OnShoot3;
                @Shoot4.started += instance.OnShoot4;
                @Shoot4.performed += instance.OnShoot4;
                @Shoot4.canceled += instance.OnShoot4;
                @Shoot5.started += instance.OnShoot5;
                @Shoot5.performed += instance.OnShoot5;
                @Shoot5.canceled += instance.OnShoot5;
                @Shoot6.started += instance.OnShoot6;
                @Shoot6.performed += instance.OnShoot6;
                @Shoot6.canceled += instance.OnShoot6;
                @Shoot7.started += instance.OnShoot7;
                @Shoot7.performed += instance.OnShoot7;
                @Shoot7.canceled += instance.OnShoot7;
                @Shoot8.started += instance.OnShoot8;
                @Shoot8.performed += instance.OnShoot8;
                @Shoot8.canceled += instance.OnShoot8;
                @Shoot9.started += instance.OnShoot9;
                @Shoot9.performed += instance.OnShoot9;
                @Shoot9.canceled += instance.OnShoot9;
                @Pause.started += instance.OnPause;
                @Pause.performed += instance.OnPause;
                @Pause.canceled += instance.OnPause;
            }
        }
    }
    public PlayerActions @Player => new PlayerActions(this);
    public interface IPlayerActions
    {
        void OnShoot0(InputAction.CallbackContext context);
        void OnShoot1(InputAction.CallbackContext context);
        void OnShoot2(InputAction.CallbackContext context);
        void OnShoot3(InputAction.CallbackContext context);
        void OnShoot4(InputAction.CallbackContext context);
        void OnShoot5(InputAction.CallbackContext context);
        void OnShoot6(InputAction.CallbackContext context);
        void OnShoot7(InputAction.CallbackContext context);
        void OnShoot8(InputAction.CallbackContext context);
        void OnShoot9(InputAction.CallbackContext context);
        void OnPause(InputAction.CallbackContext context);
    }
}
